ngoproject/carts/urls.py
from django.conf.urls import url

from .views import (
        cart_home, 
        cart_update, 
        checkout_home,
        checkout_done_view
        )

urlpatterns = [
    url(r'^$', cart_home, name='home'),
    url(r'^checkout/success/$', checkout_done_view, name='success'),
    url(r'^checkout/$', checkout_home, name='checkout'),
    url(r'^update/$', cart_update, name='update'),
]

ngoproject/donation/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'donation'

urlpatterns = [
    path('manage', views.UserList.as_view(), name='user_list'),
    path('add', views.UserCreate.as_view(), name='user_create'),
    path('update/<slug:pk>', views.UserUpdate.as_view(), name='user_update'), 
    path('delete/<slug:pk>', views.UserDelete.as_view(), name='user_delete'),
    
    path('donations', views.DonationList.as_view(), name='donation_list'), 
    path('newdonationtype', views.DonationCreateType.as_view(), name='donationtype_create'),

    path('contribute', views.UserView.as_view(), name='user_view'),
    path('donate/<slug:slug>', views.UserDonate.as_view(), name='user_donate'),
   

    path('cart', views.Cart.as_view(), name='cart')
]

ngoproject/ngoproject/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from . import settings
from django.contrib.staticfiles.urls import static

urlpatterns = [
    path('', include('donation.urls', namespace='donation')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

ngoproject/carts/models.py
# https://github.com/codingforentrepreneurs/eCommerce.git
# ^ for reverence for entire carts app
from django.db import models

# Create your models here.
from decimal import Decimal
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save, post_save, m2m_changed

from donation.models import Donation


User = settings.AUTH_USER_MODEL

class CartManager(models.Manager):
    def new_or_get(self, request):
        cart_id = request.session.get("cart_id", None)
        qs = self.get_queryset().filter(id=cart_id)
        if qs.count() == 1:
            new_obj = False
            cart_obj = qs.first()
            if request.user.is_authenticated() and cart_obj.user is None:
                cart_obj.user = request.user
                cart_obj.save()
        else:
            cart_obj = Cart.objects.new(user=request.user)
            new_obj = True
            request.session['cart_id'] = cart_obj.id
        return cart_obj, new_obj

    def new(self, user=None):
        user_obj = None
        if user is not None:
            if user.is_authenticated():
                user_obj = user
        return self.model.objects.create(user=user_obj)

class Cart(models.Model):
    user        = models.ForeignKey(User, null=True, blank=True)
    donations    = models.ManyToManyField(Donation, blank=True)

    subtotal    = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    total       = models.DecimalField(default=0.00, max_digits=100, decimal_places=2)
    updated     = models.DateTimeField(auto_now=True)
    timestamp   = models.DateTimeField(auto_now_add=True)

    objects = CartManager()

    def __str__(self):
        return str(self.id)




def m2m_changed_cart_receiver(sender, instance, action, *args, **kwargs):
    if action == 'post_add' or action == 'post_remove' or action == 'post_clear':
        donations = instance.donations.all()
        total = 0
        for x in donations:
            total += x.price
        if instance.subtotal != total:
            instance.subtotal = total
            instance.save()

m2m_changed.connect(m2m_changed_cart_receiver, sender=Cart.donations.through)




def pre_save_cart_receiver(sender, instance, *args, **kwargs):
    if instance.subtotal > 0:
        instance.total = Decimal(instance.subtotal) * Decimal(1.08) # 8% tax
    else:
        instance.total = 0.00

pre_save.connect(pre_save_cart_receiver, sender=Cart)

ngoproject/donation/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import ReadOnlyPasswordHashField

from .models import Donation

User = get_user_model()

class UserDonateForm(forms.ModelForm):
    class Meta:
        model = Donation
        exclude = ('id', 'slug')

class UserAdminCreationForm(forms.ModelForm):
    """A form for creating new users. Includes all the required
    fields, plus a repeated password."""
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'admin')

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserAdminCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user



class UserAdminChangeForm(forms.ModelForm):
    """A form for updating users. Includes all the fields on
    the user, but replaces the password field with admin's
    password hash display field.
    """
    password = ReadOnlyPasswordHashField()

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'password', 'active', 'admin')

    def clean_password(self):
        # Regardless of what the user provides, return the initial value.
        # This is done here, rather than on the field, because the
        # field does not have access to the initial value
        return self.initial["password"]



class GuestForm(forms.Form):
    email    = forms.EmailField()


class LoginForm(forms.Form):
    username = forms.EmailField(label='Email')
    password = forms.CharField(widget=forms.PasswordInput)



class RegisterForm(forms.Form):
    username = forms.CharField()
    email    = forms.EmailField()
    password = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(label='Confirm password', widget=forms.PasswordInput)

    def clean_username(self):
        username = self.cleaned_data.get('username')
        qs = User.objects.filter(username=username)
        if qs.exists():
            raise forms.ValidationError("Username is taken")
        return username

    def clean_email(self):
        email = self.cleaned_data.get('email')
        qs = User.objects.filter(email=email)
        if qs.exists():
            raise forms.ValidationError("email is taken")
        return email

    def clean(self):
        data = self.cleaned_data
        password = self.cleaned_data.get('password')
        password2 = self.cleaned_data.get('password2')
        if password2 != password:
            raise forms.ValidationError("Passwords must match.")
        return data

ngoproject/carts/views.py
from django.http import JsonResponse
from django.shortcuts import render, redirect


from donation.forms import LoginForm, GuestForm

from addresses.forms import AddressForm
from addresses.models import Address

from billing.models import BillingProfile
from orders.models import Order
from donation.models import Product
from .models import Cart


def cart_detail_api_view(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    products = [{
            "id": x.id,
            "url": x.get_absolute_url(),
            "name": x.name, 
            "price": x.price
            } 
            for x in cart_obj.products.all()]
    cart_data  = {"products": products, "subtotal": cart_obj.subtotal, "total": cart_obj.total}
    return JsonResponse(cart_data)

def cart_home(request):
    cart_obj, new_obj = Cart.objects.new_or_get(request)
    return render(request, "carts/home.html", {"cart": cart_obj})


def cart_update(request):
    product_id = request.POST.get('product_id')
    
    if product_id is not None:
        try:
            product_obj = Product.objects.get(id=product_id)
        except Product.DoesNotExist:
            print("Show message to user, product is gone?")
            return redirect("cart:home")
        cart_obj, new_obj = Cart.objects.new_or_get(request)
        if product_obj in cart_obj.products.all():
            cart_obj.products.remove(product_obj)
            added = False
        else:
            cart_obj.products.add(product_obj) # cart_obj.products.add(product_id)
            added = True
        request.session['cart_items'] = cart_obj.products.count()
        # return redirect(product_obj.get_absolute_url())
        if request.is_ajax(): # Asynchronous JavaScript And XML / JSON
            print("Ajax request")
            json_data = {
                "added": added,
                "removed": not added,
                "cartItemCount": cart_obj.products.count()
            }
            return JsonResponse(json_data, status=200) # HttpResponse
            # return JsonResponse({"message": "Error 400"}, status=400) # Django Rest Framework
    return redirect("cart:home")



def checkout_home(request):
    cart_obj, cart_created = Cart.objects.new_or_get(request)
    order_obj = None
    if cart_created or cart_obj.products.count() == 0:
        return redirect("cart:home")  
    
    login_form = LoginForm()
    guest_form = GuestForm()
    address_form = AddressForm()
    billing_address_id = request.session.get("billing_address_id", None)
    shipping_address_id = request.session.get("shipping_address_id", None)

    billing_profile, billing_profile_created = BillingProfile.objects.new_or_get(request)
    address_qs = None
    if billing_profile is not None:
        if request.user.is_authenticated():
            address_qs = Address.objects.filter(billing_profile=billing_profile)
        order_obj, order_obj_created = Order.objects.new_or_get(billing_profile, cart_obj)
        if shipping_address_id:
            order_obj.shipping_address = Address.objects.get(id=shipping_address_id)
            del request.session["shipping_address_id"]
        if billing_address_id:
            order_obj.billing_address = Address.objects.get(id=billing_address_id) 
            del request.session["billing_address_id"]
        if billing_address_id or shipping_address_id:
            order_obj.save()

    if request.method == "POST":
        "check that order is done"
        is_done = order_obj.check_done()
        if is_done:
            order_obj.mark_paid()
            request.session['cart_items'] = 0
            del request.session['cart_id']
            return redirect("cart:success")
    context = {
        "object": order_obj,
        "billing_profile": billing_profile,
        "login_form": login_form,
        "guest_form": guest_form,
        "address_form": address_form,
        "address_qs": address_qs,
    }
    return render(request, "carts/checkout.html", context)







def checkout_done_view(request):
    return render(request, "carts/checkout-done.html", {})






from django.shortcuts import render

# Create your views here.

ngoproject/donation/views.py
from django.shortcuts import render, get_object_or_404, HttpResponseRedirect
from .models import *
from .forms import UserAdminCreationForm, UserDonateForm
from django.views.generic import CreateView, ListView, DeleteView, UpdateView, FormView
from django.contrib.auth.mixins import LoginRequiredMixin

# Create your views here.

class UserList(LoginRequiredMixin,ListView):
    model = User
    template_name = 'donation/user_list.html'
    context_object_name = 'user_list'

class UserCreate(LoginRequiredMixin, CreateView):
    model = User
    template_name = 'donation/user_create.html'
    form_class = UserAdminCreationForm
    
    context_object_name = 'user_create'

    def form_valid(self, form):
        form.instance.created_by = self.request.user
        return super().form_valid(form)
    success_url = '/manage'

class UserDelete(LoginRequiredMixin,DeleteView):
    model = User
    template_name = 'donation/user_delete.html'
    
    success_url = '/manage'

class UserUpdate(LoginRequiredMixin,UpdateView):
    model = User
    template_name = 'donation/user_update.html'
    fields = ['first_name', 'last_name', 'email', 'role_opt']
    success_url = '/manage'




class DonationList(LoginRequiredMixin, ListView):
    model = Donation
    template_name = 'donation/donation_list.html'
    context_object_name = 'donation_list'

class DonationCreateType(LoginRequiredMixin, CreateView):
    model = Donation
    template_name = 'donation/donationtype_create.html'
    fields = ['donation_type', 'slug']

    success_url = '/donations'


# contribute page
class UserView(LoginRequiredMixin, ListView):
    model = Donation
    template_name = 'donation/user_view.html'
    context_object_name = 'donation_type'
# user donation form
class UserDonate(LoginRequiredMixin,CreateView):
    model = Donation
    template_name ='donation/donation_create.html'
    form_class = UserDonateForm




class Cart(LoginRequiredMixin, ListView):
    model = Cart

    template_name = 'donation/cart.html'
    context_object_name = 'cart'

ngoproject/donation/templates/donation/cart.html
This is /cart

ngoproject/donation/templates/donation/donation_create.html
{% extends '../base.html' %}

{% block title%} Personal Info {% endblock title%}

{% block content %}
    <h1> Personal Information </h1>
    <form method="post" action="{% url 'donation:cart' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Continue" class='button'>
        <a href="{% url 'donation:user_view' %}" role='button' > Cancel </a>
    </form>
{% endblock content %}

ngoproject/donation/templates/donation/donation_list.html
{% extends '../base.html' %}

{% block title%} Donation Management {% endblock title%}

{% block content %}
    <h1>Donation Management</h1>
    <!-- Do we want a button to add donation types? -->
    <div class='container'>
        <div class="float-end">
            <a class="btn btn-primary" role="button" href="{% url 'donation:donationtype_create' %}">
            <!-- Find FA icon for donation type button -->
                <i class="fas fa-user-plus"></i>
                <span>Add Donation Type</span>
            </a>
        </div>
        <table class='table table-striped'>
            <thead class='table-dark'>
                <tr>
                    <th>Name</th>
                    <th>Date</th> 
                    <th>Amount</th>
                    <th>Donation Type</th>
                </tr>
            </thead>
            <tbody>
            {% if donation_list %}
                {% for donation in donation_list %}
                    {% if donation.donation_amount != None %}
                        <tr>
                            <td> {{ donation.first_name }} {{ donation.last_name }} </td>
                            <td> {{ donation.date_created }} </td>
                            <td> {{ donation.donation_amount }} </td>
                            <td> {{ donation.donation_type }} </td>
                        </tr>
                    {% else %}
                    {% endif %}
                {% endfor %}
            {% else %}
                <p> No donation information available.</p>
            {% endif %}
            </tbody>
        </table>
    </div>
    
{% endblock content %}

ngoproject/donation/templates/donation/donationtype_create.html
{% extends '../base.html' %}

{% block title%} Add New Donation Type {% endblock title%}

{% block content %}
    <h1> Add New Donation Type </h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
        <a href="{% url 'donation:donation_list' %}" > Cancel </a>
    </form>
{% endblock content %}

ngoproject/donation/templates/donation/give_donation.html
{% extends '../base.html' %}

{% block title%} Gifts {% endblock title%}

{% block content %}
    <h1> Gifts </h1>
    <form method="post" action="{% url 'donation:give_donation' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Continue" class='button'>
        <a href="{% url 'donation:user_view' %}" role='button' > Cancel </a>
    </form>
{% endblock content %}

ngoproject/donation/templates/donation/user_create.html
{% extends '../base.html' %}

{% block title%} Add New User {% endblock title%}

{% block content %}
    <h1> Add New User </h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
        <a href="{% url 'donation:user_list' %}" > Cancel </a>
    </form>
{% endblock content %}

ngoproject/donation/templates/donation/user_delete.html
{% extends '../base.html' %}

{% block title %} Delete Product {% endblock title %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <p>Are you sure you want to delete '{{ object }}'?</p>
        <input type="submit" value="Confirm" />
        <a href="{% url 'donation:user_list' %}" > Cancel </a>
    </form>
{% endblock content %}

ngoproject/donation/templates/donation/user_list.html
{% extends '../base.html' %}

{% block title%} User Management {% endblock title%}

{% block content %}
    <h1>User Management</h1>
    
    <div class='container'>
        <div class="float-end">
            <a class="btn btn-primary" role="button" href="{% url 'donation:user_create' %}">
                <i class="fas fa-user-plus"></i>
                <span>Add User</span>
            </a>
        </div>
        <table class='table table-striped'>
            <thead class='table-dark'>
                <tr>
                    <th>First name</th>
                    <th>Last name</th> 
                    <th>Email</th>
                    <th>Role</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% if user_list %}
                {% for user in user_list %}
                    <tr>
                        <td> {{ user.first_name }} </td>
                        <td> {{ user.last_name }} </td>
                        <td> {{ user.email }} </td>
                        <td> {% if user.is_admin %}Admin{% else %} User {% endif %} </td>
                        <td><a href="{% url 'donation:user_update' pk=user.id %}"> edit </a></td> 
                        <td><a href="{% url 'donation:user_delete' pk=user.id %}"> delete </a></td> 
                    </tr>
                {% endfor %}
            {% else %}
                <p> No users available.</p>
            {% endif %}
            </tbody>
        </table>
    </div>
    
{% endblock content %}

ngoproject/donation/templates/donation/user_update.html
{% extends '../base.html' %}

{% block title%} Edit User {% endblock title%}

{% block content %}
    <h1> Edit User </h1>
    <form method="post">{% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Save">
        <a href="{% url 'donation:user_list' %}" > Cancel </a>
    </form>
{% endblock content %}

ngoproject/donation/templates/donation/user_view.html
{% extends '../base.html' %}

{% block title%} Make a Donation {% endblock title%}

{% block content %}
    <div class="">
        <h1>Make a Donation</h1>
    </div>

    <p>Click on any Donation Type to continue</p>

    <div class='d-grid gap-2 d-md-flex justify-content-md-start'>
    
        {% if donation_type %}
            {% for donation in donation_type %}
                {% if donation.slug %}
                    <a href='{% url 'donation:user_donate' donation.slug %}' class='btn btn-primary me-md-2' role='button'> {{ donation.donation_type }} </a>
                {% endif %}
            {% endfor %}
        {% else %}
            <p> No donations available.</p>
        {% endif %}
        
    </div>
    
{% endblock content %}